version: "3"

services:
  app-node:
    build: .
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/home/node/app-node
    networks:
      - my-network

  api-desafio-backend-pg:
    # build: ./pg_rs
    image: bitnami/postgresql
    # volumes:
    #   - ./pgdb_data:/bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apidesafiobackend
    networks:
      - my-network

volumes:
  pgdb_data:
    driver: local

networks:
  my-network:
    external: true
    driver: bridge
